accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

eventcalendar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('filemanager/', include('filemanager.urls', namespace='filemanager')),
    path('', RedirectView.as_view(url='/accounts/signin/', permanent=True))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filemanager/urls.py
from django.urls import path
from .views import upload_file, file_list, map_line_view, dashboard, edit_profile, map_polygon_view, download_heightmap_file

app_name = 'filemanager'

urlpatterns = [
    path('upload/', upload_file, name='file_upload'),
    path('files/', file_list, name='file_list'),
    path('map_line/', map_line_view, name='map_line_view_default'),
    path('map_line/<int:file_id>/', map_line_view, name='map_line_view'),
    path('map_polygon/<int:file_id>/', map_polygon_view, name='map_polygon_view'),
    path('download_heightmap_file/<int:file_id>', download_heightmap_file, name='download_heightmap_file'),
    path('dashboard/', dashboard, name='dashboard'),
    path('profile/', edit_profile, name='profile'),
]

filemanager/models.py
from django.db import models
from django.conf import settings

class UploadedFile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='files')
    file = models.FileField(upload_to='user_files/%Y/%m/%d')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email} - {self.file.name}"

filemanager/forms.py
from django import forms
from .models import UploadedFile
from django.contrib.auth import get_user_model


class FileUploadForm(forms.ModelForm):
    class Meta:
        model = UploadedFile
        fields = ['file']

User = get_user_model()

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'image', 'description', 'department']
        widgets = {
            'email': forms.EmailInput(attrs={'readonly': 'readonly'}),
        }

filemanager/views.py
import numpy as np
import plotly
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from matplotlib import pyplot as plt
import contextily as ctx
from .forms import FileUploadForm, UserProfileForm
from .models import UploadedFile
import geopandas as gpd
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import plotly.express as px
import plotly.graph_objects as go
from modules import processing as prc, contours as cnt
from .utils import load_geojson, validate_data, project_geometry
import os
from django.conf import settings


@login_required
def upload_file(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['file']
            if uploaded_file.name.endswith('.geojson'):
                uploaded_file = form.save(commit=False)
                uploaded_file.user = request.user
                uploaded_file.save()
                return redirect('filemanager:file_list')
            else:
                form.add_error('file', 'Загружаемый файл должеть иметь расширение ".geojson".')
    else:
        form = FileUploadForm()
    return render(request, 'filemanager/upload_file.html', {'form': form})

#moduls/geojson_to_heightmap.py (author: https://github.com/16Shadows/GeoJsonToHeightMap/commits?author=KosmixGT)
@login_required
def download_heightmap_file(request, file_id):
    uploaded_file = UploadedFile.objects.get(id=file_id, user=request.user)
    uploaded_file_path = uploaded_file.file.path
    heightmap_file_name = uploaded_file.file.name + "heightmap.txt"

    left_bottom = (39.395158, 52.491465)
    left_bottom_projected = prc.wgs84_point_to_crs(left_bottom, prc.MSK_48_CRS)
    right_top = (39.829939, 52.683001)
    right_top_projected = prc.wgs84_point_to_crs(right_top, prc.MSK_48_CRS)

    # Загружаем и валидируем данные в заданной области
    df_culled = load_geojson(uploaded_file_path, left_bottom, right_top)
    validate_data(df_culled)

    # Преобразуем контуры в полигоны и проецируем в систему координат MSK-48
    df_projected = project_geometry(df_culled, prc.MSK_48_CRS)
    df_polygons = cnt.contours_to_polygons(df_projected)

    # Вычисляем размер сетки сэмплирования
    step_size = 10  # Шаг сэмплирования (в метрах) - расстояние между точками сетки
    column_count = 2000  # Количество столбцов в сетке
    row_count = 2000  # Количество строк в сетке

    # Генерируем сетку сэмплирования
    sampling_grid = prc.generate_sampling_grid(
        leftTop=(int(left_bottom_projected[0]), int(right_top_projected[1])),  # Координаты левого верхнего угла сетки
        stepSize=step_size,  # Шаг сэмплирования (расстояние между точками)
        columnCount=column_count,  # Количество столбцов в сетке
        rowCount=row_count,  # Количество строк в сетке
        crs=prc.MSK_48_CRS,  # Система координат сетки
    )

    # Присваиваем высоты точкам сетки
    heightmap = prc.generate_height_map(df_polygons, sampling_grid)

    # Получаем карту высот в виде списка списков
    height_lists = prc.height_map_to_lists(heightmap)

    # Запись полученных данных
    heightmap_file = ""
    heightmap_file += f"ncols {column_count}\n"
    heightmap_file += f"nrows {row_count}\n"
    heightmap_file += f"xllcorner {int(left_bottom_projected[0])}\n"
    heightmap_file += f"yllcorner {int(left_bottom_projected[1])}\n"
    heightmap_file += f"cellsize {step_size}\n"
    heightmap_file += "NODATA_value -99999     Unit μg/m3\n"

    for row in height_lists:
        heightmap_file += ' '.join(map(str, row)) + '\n'

    # Возвращаем файл в виде HttpResponse
    response = HttpResponse(heightmap_file, content_type="text/plain")
    response['Content-Disposition'] = f'attachment; filename="{heightmap_file_name}"'
    return response


@login_required
def file_list(request):
    files = UploadedFile.objects.filter(user=request.user)
    return render(request, 'filemanager/file_list.html', {'files': files})


@login_required
def map_line_view(request, file_id=None):
    if file_id: 
        uploaded_file = UploadedFile.objects.get(id=file_id, user=request.user)
        path = uploaded_file.file.path
    else:
        path = os.path.join(settings.MEDIA_ROOT, 'default.geojson')
    
    try:
        gdf = gpd.read_file(path)

        prc.validate_data(gdf)

        df_projected = prc.project_geometry(gdf, prc.MSK_48_CRS)

        fig_m, ax_m = plt.subplots(figsize=(6.5, 6.5))

        ax_m.set_xlim(4390000, 4420000)

        ax_m.set_ylim(6890000, 6920000)

        df_projected.to_crs(epsg=3857).plot(ax=ax_m, color='blue')

        ctx.add_basemap(ax_m, source=ctx.providers.CartoDB.Voyager)

        plt.title('EPSG:3857 из МСК-48')

        plt.savefig('static/images/map_m.png')

        fig = px.scatter_mapbox(lat=[],
                                lon=[],
                                color=[color for color in gdf['elevation']],
                                color_continuous_scale='Viridis')

        color_scale = px.colors.sequential.Viridis

        min_elevation = gdf['elevation'].min()

        max_elevation = gdf['elevation'].max()
        for line, elevation in zip(gdf.geometry, gdf['elevation']):
            normalized_value = (elevation - min_elevation) / (max_elevation - min_elevation)
            color = plotly.colors.sample_colorscale(color_scale, normalized_value)
            fig.add_trace(go.Scattermapbox(
                mode="lines",
                lon=[coord[0] for coord in line.coords],
                lat=[coord[1] for coord in line.coords],
                line=dict(color=color[0], width=2),
                customdata=[elevation] * len(line.coords),
                name="",
                hovertemplate=
                'Высота: %{customdata} м<br>' +
                'Шир: %{lat:.3f}°<br>' +
                'Долг: %{lon:.3f}°',
                showlegend=False
            ))
        center = gdf.geometry.iloc[0].coords[0]
        fig.update_layout(
            mapbox_style="carto-positron",
            mapbox_zoom=10.5,
            mapbox_center={"lat": center[1], "lon": center[0]},
            height=650,
            coloraxis_colorbar=dict(title="Высота (м)"),
            margin={"t": 20, "l": 20, "b": 0},
            mapbox_bounds={"west": center[0] - 2.5,
                           "east": center[0] + 2,
                           "south": center[1] - 1,
                           "north": center[1] + 1}
        )

        return render(request, 'filemanager/map_line.html',
                      {'plotly_data': fig.to_html(full_html=False), 'file_id': file_id})
    except Exception as e:
        return render(request, 'filemanager/map_line.html', {'error': str(e)})


@login_required
def map_polygon_view(request, file_id):
    uploaded_file = UploadedFile.objects.get(id=file_id, user=request.user)
    path = uploaded_file.file.path
    try:
        gdf = gpd.read_file(path)
        prc.validate_data(gdf)
        df_projected = prc.project_geometry(gdf, prc.MSK_48_CRS)
        df_polygons = cnt.contours_to_polygons(df_projected)
        df_polygons.set_crs(prc.MSK_48_CRS, inplace=True)
        df_polygons_wgs84 = df_polygons.to_crs(epsg=4326)
        opacity = 0.5
        cmap = cm.viridis  # выбираем цветовую карту
        norm = plt.Normalize(vmin=df_polygons_wgs84['elevation'].min(),
                             vmax=df_polygons_wgs84['elevation'].max())  # нормализуем данные
        colors = [mcolors.rgb2hex(cmap(norm(x))[:-1]) for x in
                  np.linspace(df_polygons_wgs84['elevation'].min(), df_polygons_wgs84['elevation'].max(), 10)]
        # Преобразуем каждый цвет в строку с прозрачностью
        colors_with_opacity = [f'rgba{mcolors.to_rgba(color, alpha=opacity)}' for color in colors]
        fig = px.choropleth_mapbox(df_polygons_wgs84,
                                   geojson=df_polygons_wgs84['geometry'],
                                   color_continuous_scale=colors_with_opacity,
                                   locations=df_polygons_wgs84.index,
                                   opacity=0.5,
                                   color="elevation",
                                   center={"lat": df_polygons_wgs84.geometry.iloc[0].centroid.y,
                                           "lon": df_polygons_wgs84.geometry.iloc[0].centroid.x},
                                   mapbox_style="carto-positron",
                                   zoom=10,
                                   hover_name=df_polygons_wgs84['elevation'],
                                   # hover_data={}
                                   )
        fig.update_traces(hovertemplate='Высота: %{z} м')
        fig.update_layout(height=650,  # Устанавливаем высоту графика
                          margin={"t": 0, "l": 0, "b": 0})
        return render(request, 'filemanager/map_polygon.html', 
                      {'plotly_data': fig.to_html(full_html=False), 'file_id': file_id})
    except Exception as e:
        return render(request, 'filemanager/map_polygon.html', {'error': str(e)})


@login_required
def dashboard(request):
    file_path = os.path.join(settings.MEDIA_ROOT, 'default.geojson')
    if os.path.exists(file_path):
        file_exists = True
        file_url = os.path.join(settings.MEDIA_URL, 'default.geojson')
    else:
        file_exists = False
        file_url = None
    context = {
        'file_exists': file_exists,
        'file_url': file_url,
    }
    return render(request, 'filemanager/dashboard.html', context)



@login_required
def edit_profile(request):
    user = request.user
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('filemanager:profile')
    else:
        form = UserProfileForm(instance=user)

templates/filemanager/dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block breadcrumb %}
Dashboard
{% endblock breadcrumb %}

{% block content %}

{% endblock content %}

templates/filemanager/file_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}File List{% endblock title %}

{% block breadcrumb %}
<h2>Ваши загруженные файлы</h2>
{% endblock breadcrumb %}

{% block content %}
<ul>
  {% for file in files %}
    <li>
      <a href="{% url 'filemanager:map_line_view' file.id %}">{{ file.file.name }}</a> ({{ file.uploaded_at }})
    </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/filemanager/map_line.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}User Details{% endblock title %}

{% block breadcrumb %}
Карта
{% endblock breadcrumb %}

{% block content %}
<html>
<head>
    <title>Карта</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
</head>
<body>
    <h1 style="display: flex; justify-content: space-between;">
        <div style="text-align: left; margin-left: 50px;">Первичный GeoJSON из линий</div>
        <div style="text-align: right; margin-right: 50px;">GeoJSON в EPSG:3857 из МСК</div>
    </h1>

    <div style="display: flex;">
        <div style="flex-grow: 0.58;"> {{ plotly_data|safe }} </div>
        <img src="{% static 'images/map_m.png' %}" alt="Map Image" style="margin-left: auto;">
    </div>

    <a href="{% url 'filemanager:map_polygon_view' file_id %}" class="btn btn-primary">Преобразовать в полигоны</a>
</body>
</html>
{% endblock content %}<!DOCTYPE html>

templates/filemanager/map_polygon.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}User Details{% endblock title %}

{% block breadcrumb %}
Карта
{% endblock breadcrumb %}

{% block content %}
<html>
<head>
    <title>Карта</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
</head>
<body>
    <h1>Результат в полигонах</h1>
    <div id="plotly-container">{{ plotly_data|safe }}</div>
    <div id="loader" style="display: block;">
        <p>Загрузка...</p>
    </div>

    <script>
        // Здесь вместо данных plotly_data должны быть данные, которые вы хотите загрузить
        // Сейчас они загружены прямо в шаблон, но вы можете изменить это, чтобы данные загружались асинхронно

        // Скрыть надпись "Загрузка..." после загрузки страницы
        window.addEventListener('DOMContentLoaded', (event) => {
            document.getElementById('loader').style.display = 'none';
        });
    </script>

    <!-- Сохранение карты высот -->
    <button id="download-button" class="btn btn-primary">
        Сохранить карту высот
    </button>
      
    <div id="download-status">
        <h6>Статус файла: <span id="download-status-value">...</span></h6>
    </div>
    <div id="download-time">
        <h6>Время выполнения: <span id="download-time-value">...</span> сек.</h6>
    </div>

      <script>
        let downloadTime = 0;
        let downloadInterval = null;

        document.getElementById('download-button').addEventListener('click', function() {
            
            document.getElementById('download-status-value').innerHTML = "Подготовка файла...";

            // Обнуляем время выполнения и запускаем интервал
            downloadTime = 0;
            downloadInterval = setInterval(function() {
            downloadTime++;
            document.getElementById('download-time-value').innerHTML = downloadTime;
            }, 1000);

            fetch('{% url "filemanager:download_heightmap_file" file_id %}', {
                method: 'GET',
            })
            .then(response => response.blob())
            .then(blob => {
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = '{% url "filemanager:download_heightmap_file" file_id %}';
                a.click();
                window.URL.revokeObjectURL(url);

                document.getElementById('download-status-value').innerHTML = "Файл готов. Скоро начнётся скачивание.";

                // Останавливаем интервал
                clearInterval(downloadInterval);
            });
        });
      </script>

</body>
</html>
{% endblock content %}<!DOCTYPE html>

templates/filemanager/profile.html
{% extends 'base/base.html' %}

{% block title %}Профиль{% endblock title %}
{% block breadcrumb %}
    <div>
        <h1><i class="app-menu__icon fa fa-cog"></i>Редактировать профиль</h1>
    </div>
{% endblock breadcrumb %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
    </form>
</div>
{% endblock content %}

templates/filemanager/upload_file.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Upload File{% endblock title %}

{% block breadcrumb %}
<h2>Загрузить файл geojson</h2>
{% endblock breadcrumb %}

{% block content %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Загрузить файл</button>
</form>
{% endblock content %}